#!/bin/bash

# Drop this script in /etc/NetworkManager/dispatcher.d/
# It will (en|dis)able wlan if ethernet is (dis|en)abled

if [ "$1" = "enp0s31f6" ]; then
	case "$2" in
		up)
			# Ethernet turned on, so disable wifi
			nmcli radio wifi off
			;;
		down)
			# Ethernet turned off, so enable wifi
			nmcli radio wifi on
			;;
	esac
fi
